baseURL = "https://musing-lamarr-54ca69.netlify.com"
languageCode = "en-us"
title = "Hugo Blog"
defaultContentLanguageInSubdir = true

[languages]
  [languages.fr]
    title = "Mon démonstrateur d'internationalisation à Hugo"
    contentDir = "content/fr"
    languageName = "Français"
	  weight = 2
    [languages.fr.menu]
      [[languages.fr.menu.main]]
        name = "Accueil"
        pre = "home"
        url = "/fr/"
        weight = 1
      [[languages.fr.menu.main]]
        name = "Mots clés"
        pre = "tag"
        url = "/fr/tags/"
        weight = 3
      [[languages.fr.menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/fr/blog/"
        weight = 2
  [languages.en]
    title = "My internationalization demonstrator in Hugo"
    contentDir = "content/en"
    languageName = "English"
	  weight = 1
    [languages.en.menu]
      [[languages.en.menu.main]]
        name = "Home"
        pre = "home"
        url = "/en/"
        weight = 1
      [[languages.en.menu.main]]
        name = "Tags"
        pre = "tag"
        url = "/en/tags/"
        weight = 3
      [[languages.en.menu.main]]
        name = "Blog"
        pre = "edit"
        url = "/en/blog/"
        weight = 2


[params]
  dateFormat = "Jan 2, 2006"
  homeText = "Blog in Hugo"

[permlinks]
  blog = "/:filename/"

[taxonomies]
  tag = "tags"

# See https://feathericons.com/
# The value of pre is the icon name
