backend:
  name: git-gateway
  accept_roles:
    - admin
    - editor
  repo: mayank221189/hugo-netlify-blog
  branch: development # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: static/images
public_folder: /images
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - label: 'Blog in English'
    name: 'blog-in-english'
    folder: 'content/en/blog'
    create: true
    slug: '{{name}}'
    editor:
      preview: true
    fields:
      - { label: 'Name', name: 'name', widget: 'string' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: false}
      - { label: 'Rating (scale of 1-5)', name: 'rating', widget: 'number', required: false}
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - label: 'Blog en français'
    name: 'blog-en-français'
    folder: 'content/fr/blog'
    create: true
    slug: '{{name}}'
    editor:
      preview: true
    fields:
      - { label: 'Nom', name: 'name', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Mots clés', name: 'tags', widget: 'list' }
      - { label: 'L''image sélectionnée', name: 'thumbnail', widget: 'image', required: false}
      - { label: 'Évaluation (échelle de 1 à 5)', name: 'rating', widget: 'number', required: false}
      - { label: 'Corps', name: 'body', widget: 'markdown' }